### PR TITLE
[WIP] [High priority] Fix broken wallet build

### LINKED ISSUE #533: Wallet build not working on master merges

### PR DESCRIPTION
**Pull request by yourheropaul**
Master releases can't be made successfully because the wallet app build [fails](https://ci.kowala.io/kowala-tech/kcoin/1497/19). I think this is a just a node config issue.

It can be recreated with `drone exec --local`.

Closes #533

### CODE REVIEW

**Comment by yourheropaul** [comment]
@adamking I made a little bit of progress, but it's still broken for me:

```
Error: Cannot find module 'babel-preset-env' from '/go/src/github.com/kowala-tech/kcoin/wallet-app'
```

Could you possible fix it?

**Comment by yourheropaul** [comment]
We also need to push a dev version on commit to dev.

**Comment by adamking** [comment]
I can't seem to get drone to run locally. It keeps failing with the following:

[bindings:L0:0s] + make bindings
[bindings:L1:0s] make -j 5 stringer go-bindata gencodec client/build/bin/abigen client/contracts/truffle/node_modules
[bindings:L2:0s] make[1]: Entering directory '/go/src/github.com/kowala-tech/kcoin'
[bindings:L3:0s] Installing stringer...
[bindings:L4:0s] Installing go-bindata...
[bindings:L5:0s] Installing gencodec...
[bindings:L6:0s] make[1]: 'client/build/bin/abigen' is up to date.
[bindings:L7:0s] make[1]: 'client/contracts/truffle/node_modules' is up to date.
[bindings:L8:3s] make[1]: Leaving directory '/go/src/github.com/kowala-tech/kcoin'
[bindings:L9:3s] go generate ./client/contracts/bindings/...
[bindings:L10:4s] ../../truffle/contracts/consensus/mgr/ValidatorMgr.sol:3:1: Error: Source "../../truffle/node_modules/openzeppelin-solidity/contracts/lifecycle/Pausable.sol" not found: File not found.
[bindings:L11:4s] import "openzeppelin-solidity/contracts/lifecycle/Pausable.sol";
[bindings:L12:4s] ^--------------------------------------------------------------^
[bindings:L13:4s] client/contracts/bindings/consensus/consensus.go:18: running "solc": exit status 1
[bindings:L14:4s] contracts/Compatible.sol:4:5: Warning: Function state mutability can be restricted to pure
[bindings:L15:4s]     function test() public {}
[bindings:L16:4s]     ^-----------------------^
[bindings:L17:8s] ../../truffle/contracts/oracle/OracleMgr.sol:3:1: Error: Source "../../truffle/node_modules/openzeppelin-solidity/contracts/lifecycle/Pausable.sol" not found: File not found.
[bindings:L18:8s] import "openzeppelin-solidity/contracts/lifecycle/Pausable.sol";
[bindings:L19:8s] ^--------------------------------------------------------------^
[bindings:L20:8s] client/contracts/bindings/oracle/oracle.go:12: running "solc": exit status 1
[bindings:L21:8s] ../../truffle/contracts/ownership/MultiSigWallet.sol:87:5: Warning: Defining constructors as functions with the same name as the contract is deprecated. Use "constructor(...) { ... }" instead.
[bindings:L22:8s]     function MultiSigWallet(address[] _owners, uint _required)
[bindings:L23:8s]     ^ (Relevant source part starts here and spans across multiple lines).
[bindings:L24:11s] make: *** [Makefile:90: client/contracts/bindings/consensus/gen_manager.go] Error 1
2018/07/16 13:40:44 drone_step_0 : exit code 2

Am I missing something?

**Comment by yourheropaul** [comment]
This is being fixed right now.

**Comment by yourheropaul** [comment]
Also we just discovered [`npm ci`](https://docs.npmjs.com/cli/ci), which is [much faster](https://blog.npmjs.org/post/171556855892/introducing-npm-ci-for-faster-more-reliable) than anything else and suitable for CI environments.

**Comment by yourheropaul** [comment]
@adamking The issue above should be fixed now. There a bunch of generated assets (Go bindings for the smart contract, generated code for gRPC, firmware for Trezor, etc) that weren't all in version control, and they got out of sync easily. Now they are in VC, so it should be easy to replicate the wallet build error.

**Comment by adamking** [comment]
I added a dev build and fixed yarn. I tried to get npm ci working but it chokes on dependencies of edge so I kept yarn for now.

**Comment by adamking** [comment]
@yourheropaul Can you review?

**Pull request merged**
