### PR TITLE
Put e2e logs on S3

### PR DESCRIPTION
**Pull request by acroca**
When a build fails, it will send the e2e logs to S3. I set the verbosity to 6 for a more extensive logs with the risk of being too noisy.

### CODE REVIEW

**Comment by acroca** [comment]
@JekaMas you need access to our S3 account

**Comment by jmatosp** [comment]
@acroca did you had a look into shipping to our log aggregate?

**Comment by acroca** [comment]
Maybe we should, I was looking at the logs of the build and using S3 is not very convenient.

**Comment by yourheropaul** [comment]
Shipping to logz.io might be easier

**Comment by acroca** [comment]
Do you guys mind shiping this first and move to something else later? It'll help fixing the current random erros

**Pull request merged**
