### PR TITLE
Monorepo

### PR DESCRIPTION
**Pull request by acroca**
Moves everything in this repo into a subdirectory. This repo will become the monorepo to host all other projects, but this is the first step.

- Move codebase to `client/`
- Update imports to reflect the new path
- Fix the build processes to support one level deeper sourcecode
- Put Drone yaml in the root
- Put Makefile in the root

### CODE REVIEW

**Comment by yourheropaul** [comment]
Drone expects `.drone.yml` to live in the root, which is why it's not processing the commit.

**Comment by acroca** [comment]
For a review feel free to ignore the first two commits.
The first one just moves everything to `client`, the 2nd one is the result of:
```
find client -type f -not -path "client/vendor/*" -exec sed -i 's,github.com/kowala-tech/kcoin,github.com/kowala-tech/kcoin/client,g' {} +
```

**Comment by yourheropaul** [comment]
The readme should also be in the root

**Comment by acroca** [comment]
I actually moved there too.

**Pull request merged**
